name: Clean Data

on:
  push:
    paths:
      - '**.csv'
      - '**.xlsx'

jobs:
  clean_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: pip install -r requirements.txt  

      - name: Get changed files
        id: changed_files
        run: |
          echo "::set-output name=added_files::$(echo '${{ toJSON(github.event.commits.*.added) }}' | jq -r '.[][]')"
          echo "::set-output name=modified_files::$(echo '${{ toJSON(github.event.commits.*.modified) }}' | jq -r '.[][]')"

      - name: Run cleaning script
        run: python clean.py ${{ steps.changed_files.outputs.added_files }}



